### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ostapenko-me** [frontend-park-mail-ru/2017_1_headShot777#5]
- [x] Установить WebStorm
- [ ] Линтинг
- [ ] Убрать весь php
- [ ] Избавиться от глобальных переменных
- [ ] Убрать onclick и другие инлайновые события. Только `addEventListener`
- [ ] `'use strict';`
- [ ] Динамическое создание уровней
- [ ] Все модули в виде es6-классов
- [ ] Контент страницы лежит в html но скрытый. Когда нужно, он просто отображается
- [ ] Стили по БЭМу
- [ ] Только строгое сравнение
- [ ] Единый стиль кода
